settings:
  ADMIN_TOKEN: 'b00ccdab32e0230db87ec43b01f039d3c24f6e0b'
  BASE_URL: 'http://localhost:8080/'
  DJANGO_LABEL_URL: 'api/ai-labels'
  DJANGO_MODEL_URL: 'api/ai-models' 
  DJANGO_MODEL_TYPE_URL: 'api/ai-model-types'
  DJANGO_MODEL_GROUP_URL: 'api/ai-model-groups'


spec:
  - modelName: "yolov7"
    labels: [
      {'name': 'person', 'shapeType': 'rectangle'},
      {'name': 'bicycle', 'shapeType': 'rectangle'},
      {'name': 'car', 'shapeType': 'rectangle'},
      {'name': 'motorcycle', 'shapeType': 'rectangle'},
      {'name': 'airplane', 'shapeType': 'rectangle'},
      {'name': 'bus', 'shapeType': 'rectangle'},
      {'name': 'train', 'shapeType': 'rectangle'},
      {'name': 'truck', 'shapeType': 'rectangle'},
      {'name': 'boat', 'shapeType': 'rectangle'},
      {'name': 'traffic light', 'shapeType': 'rectangle'},
      {'name': 'fire hydrant', 'shapeType': 'rectangle'},
      {'name': 'stop sign', 'shapeType': 'rectangle'},
      {'name': 'parking meter', 'shapeType': 'rectangle'},
      {'name': 'bench', 'shapeType': 'rectangle'},
      {'name': 'bird', 'shapeType': 'rectangle'},
      {'name': 'cat', 'shapeType': 'rectangle'},
      {'name': 'dog', 'shapeType': 'rectangle'},
      {'name': 'horse', 'shapeType': 'rectangle'},
      {'name': 'sheep', 'shapeType': 'rectangle'},
      {'name': 'cow', 'shapeType': 'rectangle'},
      {'name': 'elephant', 'shapeType': 'rectangle'},
      {'name': 'bear', 'shapeType': 'rectangle'},
      {'name': 'zebra', 'shapeType': 'rectangle'},
      {'name': 'giraffe', 'shapeType': 'rectangle'},
      {'name': 'backpack', 'shapeType': 'rectangle'},
      {'name': 'umbrella', 'shapeType': 'rectangle'},
      {'name': 'handbag', 'shapeType': 'rectangle'},
      {'name': 'tie', 'shapeType': 'rectangle'},
      {'name': 'suitcase', 'shapeType': 'rectangle'},
      {'name': 'frisbee', 'shapeType': 'rectangle'},
      {'name': 'skis', 'shapeType': 'rectangle'},
      {'name': 'snowboard', 'shapeType': 'rectangle'},
      {'name': 'sports ball', 'shapeType': 'rectangle'},
      {'name': 'kite', 'shapeType': 'rectangle'},
      {'name': 'baseball bat', 'shapeType': 'rectangle'},
      {'name': 'baseball glove', 'shapeType': 'rectangle'},
      {'name': 'skateboard', 'shapeType': 'rectangle'},
      {'name': 'surfboard', 'shapeType': 'rectangle'},
      {'name': 'tennis racket', 'shapeType': 'rectangle'},
      {'name': 'bottle', 'shapeType': 'rectangle'},
      {'name': 'wine glass', 'shapeType': 'rectangle'},
      {'name': 'cup', 'shapeType': 'rectangle'},
      {'name': 'fork', 'shapeType': 'rectangle'},
      {'name': 'knife', 'shapeType': 'rectangle'},
      {'name': 'spoon', 'shapeType': 'rectangle'},
      {'name': 'bowl', 'shapeType': 'rectangle'},
      {'name': 'banana', 'shapeType': 'rectangle'},
      {'name': 'apple', 'shapeType': 'rectangle'},
      {'name': 'sandwich', 'shapeType': 'rectangle'},
      {'name': 'orange', 'shapeType': 'rectangle'},
      {'name': 'broccoli', 'shapeType': 'rectangle'},
      {'name': 'carrot', 'shapeType': 'rectangle'},
      {'name': 'hot dog', 'shapeType': 'rectangle'},
      {'name': 'pizza', 'shapeType': 'rectangle'},
      {'name': 'donut', 'shapeType': 'rectangle'},
      {'name': 'cake', 'shapeType': 'rectangle'},
      {'name': 'chair', 'shapeType': 'rectangle'},
      {'name': 'couch', 'shapeType': 'rectangle'},
      {'name': 'potted plant', 'shapeType': 'rectangle'},
      {'name': 'bed', 'shapeType': 'rectangle'},
      {'name': 'dining table', 'shapeType': 'rectangle'},
      {'name': 'toilet', 'shapeType': 'rectangle'},
      {'name': 'tv', 'shapeType': 'rectangle'},
      {'name': 'laptop', 'shapeType': 'rectangle'},
      {'name': 'mouse', 'shapeType': 'rectangle'},
      {'name': 'remote', 'shapeType': 'rectangle'},
      {'name': 'keyboard', 'shapeType': 'rectangle'},
      {'name': 'cell phone', 'shapeType': 'rectangle'},
      {'name': 'microwave', 'shapeType': 'rectangle'},
      {'name': 'oven', 'shapeType': 'rectangle'},
      {'name': 'toaster', 'shapeType': 'rectangle'},
      {'name': 'sink', 'shapeType': 'rectangle'},
      {'name': 'refrigerator', 'shapeType': 'rectangle'},
      {'name': 'book', 'shapeType': 'rectangle'},
      {'name': 'clock', 'shapeType': 'rectangle'},
      {'name': 'vase', 'shapeType': 'rectangle'},
      {'name': 'scissors', 'shapeType': 'rectangle'},
      {'name': 'teddy bear', 'shapeType': 'rectangle'},
      {'name': 'hair drier', 'shapeType': 'rectangle'},
      {'name': 'toothbrush', 'shapeType': 'rectangle'}
    ]
    modelTypes:
      - name: "Common Object Detection (Dataset A)"
        modelGroups:
          - "Bounding Box Object Detection"
    gpu_usage: 0
    deploy_script: |
        cd /ssd1/lelong/backup;
        IMAGE_NAME=cvat.yolov7
        TAG_NAME=latest
        NUCLIO_PROJECT_NAME=cvat
        if [[ $(docker images -q ${IMAGE_NAME}:${TAG_NAME} 2> /dev/null) == "" ]]; then
            cd vbpo/yolov7/nuclio;
            docker build -t ${IMAGE_NAME}:${TAG_NAME} .;
        fi;
        cd /ssd1/lelong/backup;
        ./nuctl deploy yolov7 --run-image ${IMAGE_NAME}:${TAG_NAME} -f ./vbpo/yolov7/nuclio/function.yaml --project-name ${NUCLIO_PROJECT_NAME};

  - modelName: "yolov5"
    labels: [
      {'name': 'person', 'shapeType': 'rectangle'},
      {'name': 'bicycle', 'shapeType': 'rectangle'},
      {'name': 'car', 'shapeType': 'rectangle'},
      {'name': 'motorcycle', 'shapeType': 'rectangle'},
      {'name': 'airplane', 'shapeType': 'rectangle'},
      {'name': 'bus', 'shapeType': 'rectangle'},
      {'name': 'train', 'shapeType': 'rectangle'},
      {'name': 'truck', 'shapeType': 'rectangle'},
      {'name': 'boat', 'shapeType': 'rectangle'},
      {'name': 'traffic light', 'shapeType': 'rectangle'},
      {'name': 'fire hydrant', 'shapeType': 'rectangle'},
      {'name': 'stop sign', 'shapeType': 'rectangle'},
      {'name': 'parking meter', 'shapeType': 'rectangle'},
      {'name': 'bench', 'shapeType': 'rectangle'},
      {'name': 'bird', 'shapeType': 'rectangle'},
      {'name': 'cat', 'shapeType': 'rectangle'},
      {'name': 'dog', 'shapeType': 'rectangle'},
      {'name': 'horse', 'shapeType': 'rectangle'},
      {'name': 'sheep', 'shapeType': 'rectangle'},
      {'name': 'cow', 'shapeType': 'rectangle'},
      {'name': 'elephant', 'shapeType': 'rectangle'},
      {'name': 'bear', 'shapeType': 'rectangle'},
      {'name': 'zebra', 'shapeType': 'rectangle'},
      {'name': 'giraffe', 'shapeType': 'rectangle'},
      {'name': 'backpack', 'shapeType': 'rectangle'},
      {'name': 'umbrella', 'shapeType': 'rectangle'},
      {'name': 'handbag', 'shapeType': 'rectangle'},
      {'name': 'tie', 'shapeType': 'rectangle'},
      {'name': 'suitcase', 'shapeType': 'rectangle'},
      {'name': 'frisbee', 'shapeType': 'rectangle'},
      {'name': 'skis', 'shapeType': 'rectangle'},
      {'name': 'snowboard', 'shapeType': 'rectangle'},
      {'name': 'sports ball', 'shapeType': 'rectangle'},
      {'name': 'kite', 'shapeType': 'rectangle'},
      {'name': 'baseball bat', 'shapeType': 'rectangle'},
      {'name': 'baseball glove', 'shapeType': 'rectangle'},
      {'name': 'skateboard', 'shapeType': 'rectangle'},
      {'name': 'surfboard', 'shapeType': 'rectangle'},
      {'name': 'tennis racket', 'shapeType': 'rectangle'},
      {'name': 'bottle', 'shapeType': 'rectangle'},
      {'name': 'wine glass', 'shapeType': 'rectangle'},
      {'name': 'cup', 'shapeType': 'rectangle'},
      {'name': 'fork', 'shapeType': 'rectangle'},
      {'name': 'knife', 'shapeType': 'rectangle'},
      {'name': 'spoon', 'shapeType': 'rectangle'},
      {'name': 'bowl', 'shapeType': 'rectangle'},
      {'name': 'banana', 'shapeType': 'rectangle'},
      {'name': 'apple', 'shapeType': 'rectangle'},
      {'name': 'sandwich', 'shapeType': 'rectangle'},
      {'name': 'orange', 'shapeType': 'rectangle'},
      {'name': 'broccoli', 'shapeType': 'rectangle'},
      {'name': 'carrot', 'shapeType': 'rectangle'},
      {'name': 'hot dog', 'shapeType': 'rectangle'},
      {'name': 'pizza', 'shapeType': 'rectangle'},
      {'name': 'donut', 'shapeType': 'rectangle'},
      {'name': 'cake', 'shapeType': 'rectangle'},
      {'name': 'chair', 'shapeType': 'rectangle'},
      {'name': 'couch', 'shapeType': 'rectangle'},
      {'name': 'potted plant', 'shapeType': 'rectangle'},
      {'name': 'bed', 'shapeType': 'rectangle'},
      {'name': 'dining table', 'shapeType': 'rectangle'},
      {'name': 'toilet', 'shapeType': 'rectangle'},
      {'name': 'tv', 'shapeType': 'rectangle'},
      {'name': 'laptop', 'shapeType': 'rectangle'},
      {'name': 'mouse', 'shapeType': 'rectangle'},
      {'name': 'remote', 'shapeType': 'rectangle'},
      {'name': 'keyboard', 'shapeType': 'rectangle'},
      {'name': 'cell phone', 'shapeType': 'rectangle'},
      {'name': 'microwave', 'shapeType': 'rectangle'},
      {'name': 'oven', 'shapeType': 'rectangle'},
      {'name': 'toaster', 'shapeType': 'rectangle'},
      {'name': 'sink', 'shapeType': 'rectangle'},
      {'name': 'refrigerator', 'shapeType': 'rectangle'},
      {'name': 'book', 'shapeType': 'rectangle'},
      {'name': 'clock', 'shapeType': 'rectangle'},
      {'name': 'vase', 'shapeType': 'rectangle'},
      {'name': 'scissors', 'shapeType': 'rectangle'},
      {'name': 'teddy bear', 'shapeType': 'rectangle'},
      {'name': 'hair drier', 'shapeType': 'rectangle'},
      {'name': 'toothbrush', 'shapeType': 'rectangle'}
    ]
    modelTypes:
      - name: "Common Object Detection (Dataset A)"
        modelGroups:
          - "Bounding Box Object Detection"
    gpu_usage: 0
    deploy_script: 

  - modelName: "combine-licence-plate-detection"
    labels: [
      {'name': '1', 'shapeType': 'rectangle'},
      {'name': '2', 'shapeType': 'rectangle'},
      {'name': '3', 'shapeType': 'rectangle'},
      {'name': '4', 'shapeType': 'rectangle'},
      {'name': '5', 'shapeType': 'rectangle'},
      {'name': '6', 'shapeType': 'rectangle'},
      {'name': '7', 'shapeType': 'rectangle'},
      {'name': '8', 'shapeType': 'rectangle'},
      {'name': '9', 'shapeType': 'rectangle'},
      {'name': 'A', 'shapeType': 'rectangle'},
      {'name': 'B', 'shapeType': 'rectangle'},
      {'name': 'C', 'shapeType': 'rectangle'},
      {'name': 'D', 'shapeType': 'rectangle'},
      {'name': 'E', 'shapeType': 'rectangle'},
      {'name': 'F', 'shapeType': 'rectangle'},
      {'name': 'G', 'shapeType': 'rectangle'},
      {'name': 'H', 'shapeType': 'rectangle'},
      {'name': 'K', 'shapeType': 'rectangle'},
      {'name': 'L', 'shapeType': 'rectangle'},
      {'name': 'M', 'shapeType': 'rectangle'},
      {'name': 'N', 'shapeType': 'rectangle'},
      {'name': 'P', 'shapeType': 'rectangle'},
      {'name': 'S', 'shapeType': 'rectangle'},
      {'name': 'T', 'shapeType': 'rectangle'},
      {'name': 'U', 'shapeType': 'rectangle'},
      {'name': 'V', 'shapeType': 'rectangle'},
      {'name': 'X', 'shapeType': 'rectangle'},
      {'name': 'Y', 'shapeType': 'rectangle'},
      {'name': 'Z', 'shapeType': 'rectangle'},
      {'name': '0', 'shapeType': 'rectangle'},
      {'name': 'licensePlates', 'shapeType': 'rectangle'}
    ]
    modelTypes:
      - name: "License Plate Detection (Dataset D)"
        modelGroups:
          - "Bounding Box Object Detection"
    gpu_usage: 0
    deploy_script: |
        cd /ssd1/lelong/backup;
        IMAGE_NAME=cvat.combine-licence-plate-detection
        TAG_NAME=latest
        NUCLIO_PROJECT_NAME=cvat
        if [[ $(docker images -q ${IMAGE_NAME}:${TAG_NAME} 2> /dev/null) == "" ]]; then
            cd vbpo/combine-licence-plate-detection/nuclio;
            docker build -t ${IMAGE_NAME}:${TAG_NAME} .;
        fi;
        cd /ssd1/lelong/backup;
        ./nuctl deploy combine-licence-plate-detection --run-image ${IMAGE_NAME}:${TAG_NAME} -f ./vbpo/combine-licence-plate-detection/nuclio/function.yaml --project-name ${NUCLIO_PROJECT_NAME};


  - modelName: "license-plate-detection"
    labels: [
      {'name': 'licensePlates', 'shapeType': 'rectangle'}
    ]
    modelTypes:
      - name: "License Plate Detection (Dataset M)"
        modelGroups:
          - "Bounding Box Object Detection"
    gpu_usage: 0
    deploy_script: |
        cd /ssd1/lelong/backup;
        IMAGE_NAME=cvat.license-plate-detection
        TAG_NAME=latest
        NUCLIO_PROJECT_NAME=cvat
        if [[ $(docker images -q ${IMAGE_NAME}:${TAG_NAME} 2> /dev/null) == "" ]]; then
            cd vbpo/license-plate-detection/nuclio;
            docker build -t ${IMAGE_NAME}:${TAG_NAME} .;
        fi;
        cd /ssd1/lelong/backup;
        ./nuctl deploy license-plate-detection --run-image ${IMAGE_NAME}:${TAG_NAME} -f ./vbpo/license-plate-detection/nuclio/function.yaml --project-name ${NUCLIO_PROJECT_NAME};


  - modelName: "clrnet"
    labels: [
      {'name': 'line', 'shapeType': 'rectangle'}
    ]
    modelTypes:
      - name: "Road Lane Line Detection (Dataset G)"
        modelGroups:
          - "Polyline Detection"
    gpu_usage: 0
    deploy_script: |
        cd /ssd1/lelong/backup;
        PROJECT_NAME=cvat
        ./nuctl deploy --project-name ${PROJECT_NAME} --path "./vbpo/clrnet/nuclio/" --platform local;



  - modelName: "retinaface"
    labels: [
      {'name': 'left eye', 'shapeType': 'points'},
      {'name': 'right eye', 'shapeType': 'points'},
      {'name': 'mouth left', 'shapeType': 'points'},
      {'name': 'mouth right', 'shapeType': 'points'},
      {'name': 'nose', 'shapeType': 'points'},
      {'name': 'face', 'shapeType': 'rectangle'}
    ]
    modelTypes:
      - name: "Face & Five Landmark Detection"
        modelGroups:
          - "Bounding Box Object Detection"
          - "Landmark Point Detection"
    gpu_usage: 0
    deploy_script: |
        cd /ssd1/lelong/backup;
        PROJECT_NAME=cvat
        ./nuctl deploy --project-name ${PROJECT_NAME} --path "./vbpo/retina/nuclio/" --platform local;


  - modelName: "mask.transfiner"
    labels: [
      {'name': 'electronic', 'shapeType': 'polygon'},
      {'name': 'appliance', 'shapeType': 'polygon'},
      {'name': 'food', 'shapeType': 'polygon'},
      {'name': 'furniture', 'shapeType': 'polygon'},
      {'name': 'indoor', 'shapeType': 'polygon'},
      {'name': 'kitchen', 'shapeType': 'polygon'},
      {'name': 'accessory', 'shapeType': 'polygon'},
      {'name': 'animal', 'shapeType': 'polygon'},
      {'name': 'outdoor', 'shapeType': 'polygon'},
      {'name': 'person', 'shapeType': 'polygon'},
      {'name': 'sports', 'shapeType': 'polygon'},
      {'name': 'vehicle', 'shapeType': 'polygon'},
      {'name': 'ceiling', 'shapeType': 'polygon'},
      {'name': 'floor', 'shapeType': 'polygon'},
      {'name': 'food_2', 'shapeType': 'polygon'},
      {'name': 'furniture_2', 'shapeType': 'polygon'},
      {'name': 'rawmaterial', 'shapeType': 'polygon'},
      {'name': 'textile', 'shapeType': 'polygon'},
      {'name': 'wall', 'shapeType': 'polygon'},
      {'name': 'window', 'shapeType': 'polygon'},
      {'name': 'building', 'shapeType': 'polygon'},
      {'name': 'ground', 'shapeType': 'polygon'},
      {'name': 'plant', 'shapeType': 'polygon'},
      {'name': 'sky', 'shapeType': 'polygon'},
      {'name': 'solid', 'shapeType': 'polygon'},
      {'name': 'structural', 'shapeType': 'polygon'},
      {'name': 'water', 'shapeType': 'polygon'},
      {'name': 'electronic', 'shapeType': 'mask'},
      {'name': 'appliance', 'shapeType': 'mask'},
      {'name': 'food', 'shapeType': 'mask'},
      {'name': 'furniture', 'shapeType': 'mask'},
      {'name': 'indoor', 'shapeType': 'mask'},
      {'name': 'kitchen', 'shapeType': 'mask'},
      {'name': 'accessory', 'shapeType': 'mask'},
      {'name': 'animal', 'shapeType': 'mask'},
      {'name': 'outdoor', 'shapeType': 'mask'},
      {'name': 'person', 'shapeType': 'mask'},
      {'name': 'sports', 'shapeType': 'mask'},
      {'name': 'vehicle', 'shapeType': 'mask'},
      {'name': 'ceiling', 'shapeType': 'mask'},
      {'name': 'floor', 'shapeType': 'mask'},
      {'name': 'food_2', 'shapeType': 'mask'},
      {'name': 'furniture_2', 'shapeType': 'mask'},
      {'name': 'rawmaterial', 'shapeType': 'mask'},
      {'name': 'textile', 'shapeType': 'mask'},
      {'name': 'wall', 'shapeType': 'mask'},
      {'name': 'window', 'shapeType': 'mask'},
      {'name': 'building', 'shapeType': 'mask'},
      {'name': 'ground', 'shapeType': 'mask'},
      {'name': 'plant', 'shapeType': 'mask'},
      {'name': 'sky', 'shapeType': 'mask'},
      {'name': 'solid', 'shapeType': 'mask'},
      {'name': 'structural', 'shapeType': 'mask'},
      {'name': 'water', 'shapeType': 'mask'}
    ]
    modelTypes:
      - name: "Common Instance Segmentation (Dataset E)"
        modelGroups:
          - "Instance Segmentation"
    gpu_usage: 0
    deploy_script: |
        cd /ssd1/lelong/backup;
        PROJECT_NAME=cvat
        ./nuctl deploy --project-name ${PROJECT_NAME} --path "./vbpo/transfiner/nuclio/" --platform local;

  - modelName: "fashion.keypoint.kgdet"
    labels: [
      {'name': 'short sleeved shirt', 'shapeType': 'skeleton'},
      {'name': 'long sleeved shirt', 'shapeType': 'skeleton'},
      {'name': 'short sleeved outwear', 'shapeType': 'skeleton'},
      {'name': 'long sleeved outwear', 'shapeType': 'skeleton'},
      {'name': 'vest', 'shapeType': 'skeleton'},
      {'name': 'sling', 'shapeType': 'skeleton'},
      {'name': 'shorts', 'shapeType': 'skeleton'},
      {'name': 'trousers', 'shapeType': 'skeleton'},
      {'name': 'skirt', 'shapeType': 'skeleton'},
      {'name': 'short sleeved dress', 'shapeType': 'skeleton'},
      {'name': 'long sleeved dress', 'shapeType': 'skeleton'},
      {'name': 'vest dress', 'shapeType': 'skeleton'},
      {'name': 'sling dress', 'shapeType': 'skeleton'}
    ]
    modelTypes:
      - name: "Fashion Keypoint Detection (Dataset G)"
        modelGroups:
          - "Skeleton-based Keypoints Detection"
    gpu_usage: 0
    deploy_script: |
        cd /ssd1/lelong/backup;
        PROJECT_NAME=cvat
        ./nuctl deploy --project-name ${PROJECT_NAME} --path "./vbpo/fashion-keypoint/nuclio/" --platform local;








